### PR TITLE
updates github star design

### PR DESCRIPTION
**Pull request by jakebogan01**
I updated the github star icon design. I also tested it on multiple browsers in desktop and mobile.

Screenshot 2024-04-18 133857
Screenshot 2024-04-18 133907

### CODE REVIEW

**Review by xuelink — APPROVED** [review]

**Review by xuelink — APPROVED** [review]
Perfect! Thank you

**Review by xuelink — COMMENTED** [review]
Done

**Comment by xuelink** [comment]
#31

**Comment by jakebogan01** [comment]
@xuelink No problem 👍

**Pull request merged**
