### PR TITLE
updates announcement banner

### PR DESCRIPTION
**Pull request by jakebogan01**
@xuelink  I decided to update the look of the announcement banner, let me know what you think

Screenshot 2024-05-24 at 11 57 03 PM

### CODE REVIEW

**Comment by jakebogan01** [comment]
@xuelink I created a PR [here](https://github.com/langx/website/pull/73)

**Review by xuelink — APPROVED** [review]
Well Done!

**Comment by xuelink** [comment]
It looks awesome! Thank you @jakebogan01

**Comment by jakebogan01** [comment]
@xuelink no problem!

**Pull request merged**
